---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements

    - id: requirements-txt-fixer
    # - id: no-commit-to-branch

  - repo: https://github.com/rwxd/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: shellcheck
        exclude: |
          (?x)^(
            bin/.local/bin/workspace-ansible-playbook|
            zsh/.p10k.zsh|
            zsh/.zshrc|
            bash/.bash_profile|
          )$
      - id: shfmt
        exclude: |
          (?x)^(
            bin/.local/bin/workspace-ansible-playbook|
            zsh/.p10k.zsh|
            zsh/.zshrc|
            bash/.bash_profile|
          )$
