# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true
  
  install:
    desc: install dotfiles
    cmds:
      - |
        for folder in `ls -d */`; do
          stow -v -t ~ $folder
        done
    silent: true
  
  clean:
    desc: clean dotfiles
    cmds:
      - |
        for folder in `ls -d */`; do
          stow -v -D -t ~ $folder
        done
    silent: true
