# https://taskfile.dev

version: '3'

vars:
  LIST_DIRS_COMMAND: find . -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | grep -v '\.'

tasks:
  default:
    cmds:
      - task -l
    silent: true
  
  install:
    desc: install dotfiles
    cmds:
      - |
        for folder in `{{.LIST_DIRS_COMMAND}}`; do
          stow -v -t ~ $folder
        done
    silent: true
  
  clean:
    desc: clean dotfiles
    cmds:
      - |
        for folder in `{{.LIST_DIRS_COMMAND}}`; do
          stow -v -D -t ~ $folder
        done
    silent: true
